### ISSUE TITLE
"Access is not allowed because you are using a personal device"

### ISSUE THREAD

**Issue by entrity** [dzflack/duo-device-health#4]
Cool utility. I'm not finding success with it, though. I'm getting this failure message in the browser:
![image](https://user-images.githubusercontent.com/950824/150882766-14343644-8a4e-4147-9fb0-2127f6982347.png)

<details>
<summary>Here's the output from the go script</summary>

```
2022/01/24 15:35:01 Listening on port 53106
POST /v1/healthapp/device/health?_req_trace_group=6031fe208fb8afc6313b373e_a99be0c6a358f205a50be3e3?_=1643067323 HTTP/1.1
Host: 2.endpointhealth.duosecurity.com
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-au
Connection: close
Content-Type: application/json
User-Agent: Duo%20Device%20Health/3.4.0.0 CFNetwork/1125.2 Darwin/20.4.0 (x86_64)

{"health_check_start_timestamp":"2022-01-24 15:35:22","is_password_set":true,"health_check_end_timestamp":"2022-01-24 15:35:23","is_auto_login_enabled":false,"os":"macOS","is_encryption_enabled":true,"device_id":"DE13DE13-23F28-57A7-B81E-B81E7AE23F28","txid":"7d28f691-a559-4f4c-bf6b-5f4e76567dfd","deployment_track":"release","is_firewall_enabled":true,"duo_client_version":"3.4.0.0","os_version":"11.15.4","device_name":"work-mbp","health_check_length_millis":540.579,"os_build":"20E287","communication_scheme":"https","security_agents":null}
 

 
POST /v1/healthapp/device/health?_req_trace_group=6031fe208fb8afc6313b373e_a99be0c6a358f205a50be3e3?_=1643067323 HTTP/1.1
Host: 2.endpointhealth.duosecurity.com
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-au
Connection: close
Content-Type: application/json
User-Agent: Duo%20Device%20Health/3.4.0.0 CFNetwork/1125.2 Darwin/20.4.0 (x86_64)

{"health_check_start_timestamp":"2022-01-24 15:35:22","is_password_set":true,"health_check_end_timestamp":"2022-01-24 15:35:23","is_auto_login_enabled":false,"os":"macOS","is_encryption_enabled":true,"device_id":"DE13DE13-23F28-57A7-B81E-B81E7AE23F28","txid":"7d28f691-a559-4f4c-bf6b-5f4e76567dfd","deployment_track":"release","is_firewall_enabled":true,"duo_client_version":"3.4.0.0","os_version":"11.15.4","device_name":"work-mbp","health_check_length_millis":540.579,"os_build":"20E287","communication_scheme":"https","security_agents":null}
```
</details>

I'm a bit surprised that it makes mention of Darwin in its own user agent. I told my FF I'm using Windows. When I tell FF I'm using MacOS, it notifies me, "Your administrator needs to check if this device is approved to access this application. Next." Then it indicates I need to install the Duo Device Health application.

**Comment by dzflack** [comment]
Hey @entrity, unfortunately I'm no longer at the same employer where I had the duo-device-health app installed so I'm not really able to make any updates/fixes to this code.

> I'm a bit surprised that it makes mention of Darwin in its own user agent

The `user-agent` header is hardcoded [here](https://github.com/dzflack/duo-device-health/blob/master/main.go#L101), so you're able to modify that to a custom value.

If your admin only allows logins on approved devices, you're probably going to need to sniff a valid `DeviceID` from an approved device, and then place that value [here](https://github.com/dzflack/duo-device-health/blob/master/main.go#L69).

Additionally, I only ever tested this on a Macos host, as such there may be additional fields needed in the body that are Windows specific, and you'll probably need to supply some valid  values for the `OS`([here](https://github.com/dzflack/duo-device-health/blob/master/main.go#L67)) and `OSversion`([here](https://github.com/dzflack/duo-device-health/blob/master/main.go#L74))

**Comment by dzflack** [comment]
@entrity just out of curiosity, were you able to pull a valid `DeviceID` and log on?

**Comment by entrity** [comment]
I've got a valid DeviceID, but I haven't been able to log on with it. I suspect I need to set certain other values in my report. Unfortunately, I don't think I can find this info: my approved device (from which I got the id) doesn't appear to have duo device health app installed and isn't subject to my company's added restrictions, so I can't even download it to install it.

**Comment by ldzhjn** [comment]
@entrity @dzflack 
Can you please shed some light on how to sniff the DeviceID and other parameters needed to log on?
